Implementing admin ability to edit patient and mhwp info and split name into first name, last name
abbieDuan87/Breeze pull request #17
Opened 2024-11-16 17:26 UTC by rheahemmadi

I made quite a lot of changes so please switch to my branch and test a lot in case you find any bugs/things that may impact functionality you've changed.

Key Features:
**1. AdminService: Edit User Information Functionality**
- Added a new function edit_user_information to the AdminService class.
- The function allows the Admin to edit the first name, last name, email, and emergency contact information (emergency contact only for patients)]
- User prompts for editing user details, with conditional prompts based on the role (e.g., emergency contact is only relevant for patients).
- Added logic to display current user information to the Admin before any edits are made.

**2. PatientService Updates**
- Updated the edit_personal_information function in PatientService to work with first name, last name,

**3. Data Handling in data_utils.py (Decode User Function)**
- Updated the decode_user function to correctly parse user information (first name, last name, email, etc.) for different user roles.

**4. Updated the Admin, Patient and MHWP classes to include fields for first name, last name, and email.**
- Added getters and setters for new attributes
- Updated the to_dict method, ensuring all relevant fields are saved and loaded correctly from JSON.
<img width="585" alt="Registration" src="https://github.com/user-attachments/assets/6cc708cc-8f2d-46a5-ad81-6b48d1e85e44">
<img width="654" alt="Updates to patient personal info" src="https://github.com/user-attachments/assets/5f32f730-9c38-4d27-918f-71ced42ae466">
<img width="624" alt="Admin updating patient info" src="https://github.com/user-attachments/assets/ed6494ec-c435-4297-a9e4-44e5f13647e8">
<img width="630" alt="Admin updating mhwp info" src="https://github.com/user-attachments/assets/a9e7d191-f3a6-4e5b-8379-e7b64adebc2f">

2024-11-16 18:40 UTC, minjnlgc requested changes
Great job and well done! Just a few small suggestions:

I noticed a bug that occurs when updating other users' info, where all admins' emails are set to null. This happens because `decode_user` doesn't include the code to read the admin’s email, so the admin object created from `data.json` is missing the email attribute. As a result, when saving, it reads an empty email and writes that back to `data.json`.

Also, since you’ve added an email attribute to all user types, it might make sense to move this attribute to the parent User class to take advantage of inheritance and keep things organised in an OOP-friendly way.

2024-11-16 19:07 UTC, ben-jthompson submitted a review, later dismissed
Looks good, I encountered the same bug that Minjing got with the admin emails resetting to null. I would just make one suggestion to use the clear_screen() utility function periodically so that the user interface gets updated (eg. making sure that the admin dashboard gets cleared before you display the interface for editing data). I would probably clear the screen at the point at which the user presses E on the dashboard, as well as just before you show the updated info. Otherwise, I think it looks good; I'm not sure how the rest of the functionalities are currently looking, but perhaps we keep the Admin ascii art as a constant on the page and load it directly after we clear the screen every time.

2024-11-17 15:20 UTC, rheahemmadi commented on breeze/models/admin.py
> +    def __init__(self, username, password, first_name = None, last_name = None, email= None, is_disabled=False):
Should I also move first name and last name in that case?

2024-11-17 15:41 UTC, rheahemmadi commented on breeze/models/admin.py
> +    def __init__(self, username, password, first_name = None, last_name = None, email= None, is_disabled=False):
I moved first and last name too

2024-11-17 16:19 UTC, rheahemmadi commented on breeze/services/admin_service.py
> +        users = data.get("users", [])
removed - will show you code tomorrow in meeting. Seems to work when i test but syntax highlighting is a little odd

2024-11-17 16:19 UTC, rheahemmadi commented on breeze/services/admin_service.py
> +                updated_emergency_contact_email = input("emergency contact email: ").strip()
Done

2024-11-17 16:20 UTC, rheahemmadi commented on breeze/utils/data_utils.py
>              is_disabled=user_data.get("isDisabled", False)
added

2024-11-17 16:25 UTC, rheahemmadi commented on breeze/services/admin_service.py
> +            user = next((u for u in users if u.get_username() == username), None)
done, will show you the syntax highlighting tomorrow. It's working when I test for now

2024-11-17 16:35 UTC, rheahemmadi commented
@ben-jthompson liked the clear screen suggestion, have implemented.

2024-11-17 16:35 UTC, rheahemmadi commented
Think I have made all the changes so can re-review before merging

2024-11-17 20:32 UTC, minjnlgc submitted a review, later dismissed
It works well for me!

2024-11-17 21:31 UTC, abbieDuan87 submitted a review, later dismissed
Great work!

2024-11-18 10:16 UTC, abbieDuan87 approved these changes

2024-11-18 10:17 UTC, merged